batch_size: 20
before_example: "\nNatural language version: \""
after_example: "\" Translate the natural language version to a Lean mathlib version:\ntheorem"
in_key: "nl_statement"
out_key: "formal_statement"
save_path: "formal_of_proofwiki.jsonl"
few_shot_prompt_path: "few_shot_prompts/formal_of_proofwiki_prompt.txt"
data_path: "make_proofwiki/proofwiki.jsonl"
stop: ":="
max_tokens: 275

